name: Generate Articles JSON

on:
  schedule:
    # Uruchamiaj co 30 minut
    - cron: '*/30 * * * *'
  workflow_dispatch: # Umożliwia ręczne uruchamianie przepływu
  push:
    branches: [ main ]
    paths-ignore:
      - 'articles.json' # Ignoruj zmiany w samym pliku articles.json aby uniknąć pętli

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Generate articles.json
        run: node generate-articles.js

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add articles.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Automatyczna aktualizacja articles.json [skip ci]" && git push)